// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6919.powerUp;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainleftFrontMotor;
    public static WPI_TalonSRX driveTrainleftRearMotor;
    public static SpeedControllerGroup driveTrainleftMotors;
    public static WPI_TalonSRX driveTrainrightFrontMotor;
    public static WPI_TalonSRX driveTrainrightRearMotor;
    public static SpeedControllerGroup driveTrainrightMotors;
    public static DifferentialDrive driveTraindifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainleftFrontMotor = new WPI_TalonSRX(0);
        
        
        driveTrainleftRearMotor = new WPI_TalonSRX(1);
        
        
        driveTrainleftMotors = new SpeedControllerGroup(driveTrainleftFrontMotor, driveTrainleftRearMotor  );
        LiveWindow.addActuator("driveTrain", "leftMotors", driveTrainleftMotors);
        
        driveTrainrightFrontMotor = new WPI_TalonSRX(2);
        
        
        driveTrainrightRearMotor = new WPI_TalonSRX(3);
        
        
        driveTrainrightMotors = new SpeedControllerGroup(driveTrainrightFrontMotor, driveTrainrightRearMotor  );
        LiveWindow.addActuator("driveTrain", "rightMotors", driveTrainrightMotors);
        
        driveTraindifferentialDrive = new DifferentialDrive(driveTrainleftMotors, driveTrainrightMotors);
        LiveWindow.addActuator("driveTrain", "differentialDrive", driveTraindifferentialDrive);
        driveTraindifferentialDrive.setSafetyEnabled(true);
        driveTraindifferentialDrive.setExpiration(0.1);
        driveTraindifferentialDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
